// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB64X0nlkfL6bYbNPecbv4XZjEgfL89KwE',
    appId: '1:81099064274:web:0da1835e983b2693623e0b',
    messagingSenderId: '81099064274',
    projectId: 'pdg-otcare-72f5c',
    authDomain: 'pdg-otcare-72f5c.firebaseapp.com',
    storageBucket: 'pdg-otcare-72f5c.appspot.com',
    measurementId: 'G-5RDEJYVQDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkOyStyaNcNa6CvRSvWwY1BHfrdh6LvjQ',
    appId: '1:81099064274:android:81022f0ecd3593e4623e0b',
    messagingSenderId: '81099064274',
    projectId: 'pdg-otcare-72f5c',
    storageBucket: 'pdg-otcare-72f5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDynBQyD1a8xDJ1SfZgUY4qJ1S03xpHWU4',
    appId: '1:81099064274:ios:a3dd936f7ef28337623e0b',
    messagingSenderId: '81099064274',
    projectId: 'pdg-otcare-72f5c',
    storageBucket: 'pdg-otcare-72f5c.appspot.com',
    iosClientId: '81099064274-k6svi9n451k795qor0ls4hrle8onsfuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdgApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDynBQyD1a8xDJ1SfZgUY4qJ1S03xpHWU4',
    appId: '1:81099064274:ios:a3dd936f7ef28337623e0b',
    messagingSenderId: '81099064274',
    projectId: 'pdg-otcare-72f5c',
    storageBucket: 'pdg-otcare-72f5c.appspot.com',
    iosClientId: '81099064274-k6svi9n451k795qor0ls4hrle8onsfuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdgApp',
  );
}
